### ISSUE TITLE
Ошибка получения прав доступа к товарам.

### ISSUE THREAD

**Issue by MaxStik** [fn12gl34/vk-scraper#1]
Traceback консоли:
```
Traceback (most recent call last):
  File "C:/Users/stikh/PycharmProjects/vk-scraper-master/example.py", line 11, in <module>
    VkScraper.get_full_stat(scraper)
  File "C:\Users\stikh\PycharmProjects\vk-scraper-master\vks.py", line 32, in get_full_stat
    f_stat = scraper.get_full_stat()
  File "C:\Users\stikh\PycharmProjects\vk-scraper-master\engine\scraper.py", line 108, in get_full_stat
    goods = self.__get_goods(t)
  File "C:\Users\stikh\PycharmProjects\vk-scraper-master\engine\scraper.py", line 48, in __get_goods
    goods = vk_api_.market.get(owner_id=target, extended=True)
  File "C:\Users\stikh\PycharmProjects\vk-scraper-master\venv\lib\site-packages\vk\api.py", line 173, in __call__
    return self._api._session.make_request(self)
  File "C:\Users\stikh\PycharmProjects\vk-scraper-master\venv\lib\site-packages\vk\api.py", line 102, in make_request
    raise error
vk.exceptions.VkAPIError: 15. Access denied. request_params = {'oauth': '1', 'method': 'market.get', 'v': '8', 'owner_id': '-28905875', 'extended': 'True'}

```
Целью был этот паблик https://vk.com/rhymes

Думаю стоит просто отловить Exception и предоставить json с "error":permission-denied.

Тоже самое думаю будет и с видео и с подписчиками.

**Comment by fn12gl34** [comment]
[fixed](https://github.com/fn12gl34/vk-scraper/commit/b9255c7278b63647ffe70d08fbd779c6916ee390)
